spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/library
    username: nazaaaar
    password: loremipsum
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet